### ISSUE TITLE
Feature Request: Lightgray color variant

### ISSUE THREAD

**Issue by Lusito** [vinceliuice/Qogir-theme#101]
First off, I really like the theme. Great work!

There's just a tiny thing I would like to change: The background color being bright white is hurting my eyes. I know there is the dark theme, but that's just hurting in a different way.

I'd like to propose a gray that isn't as dark as the dark variant, but not as white as the standard variant.
I guess I could try to look into the code and try to create a PR. Just want to make sure that you are okay with this before starting work.

**Comment by vinceliuice** [comment]
Thank you for your love of my work. Since this theme has been selected as the default theme for the ubuntu budgie desktop, this theme has entered the stage of stable maintenance, so if there are major changes in appearance, I need to discuss with the team, so I think you can make this new variant yourself and publish it on your github or ping.com.

**Comment by Lusito** [comment]
Thanks for the quick response and congratulations on getting selected. Well deserved :)

**Comment by vinceliuice** [comment]
Thank you!
