### ISSUE TITLE
Remove transparency in Window Preview in panel

### ISSUE THREAD

**Issue by anuragunnikannan** [vinceliuice/Qogir-theme#290]
[cinnamon-2023-05-14T152753+0530.webm](https://github.com/vinceliuice/Qogir-theme/assets/66474656/739dd04e-6cad-4553-b1e1-bb37e6c5687d)

In Lavanda gtk theme, there is a nice border on window previews on the panel, but in Qogir-dark, it is transparent hence making it difficult to read. It would be nice, if it is made opaque as before.

**Comment by inucat** [comment]
It also affects me, but solution was found simple.

1. Open `Qogir/cinnamon/cinnamon.css`
2. Locate `.grouped-window-list-thumbnail-menu` attributes
3. As shown below, add the arrow-marked lines into the blocks. Change color as you like!

```
.grouped-window-list-thumbnail-menu .item-box {
  padding: 6px;
  border-radius: 2px;
  spacing: 4px;
  background-color: #2c2c2c; /* <--- */
}

.grouped-window-list-thumbnail-menu .item-box:selected {
  background-color: rgba(255, 255, 255, 0.33);
  background-color: #585858; /* <--- */
}
```

But this file is generated from the source css/scss files, so we need to modify them to completely fix the issue.

Unfortunately this problem is found in other themes including the ones by vinceliuice. I hope the cinnamon environment be supported well😇
