### ISSUE TITLE
Make GTK2 decorations same height as GTK3 ones

### ISSUE THREAD

**Issue by christiantosta** [vinceliuice/Qogir-theme#30]
Make GTK2 windows decorations same height as GTK3 with toolbar/menubar integrated ones. 
Follow picture shows Terminator, Gedit and Thunar for comparison.

![captura de tela_2018-12-20_21-41-57](https://user-images.githubusercontent.com/7252968/50317117-16c89280-04a1-11e9-9987-6008e3d066f6.png)

**Comment by christiantosta** [comment]
Proposed patch follows:

[Qogir-decoration.patch.txt](https://github.com/vinceliuice/Qogir-theme/files/2701199/Qogir-decoration.patch.txt)

**Comment by vinceliuice** [comment]
I think this will make non-csd windows looks not so good on Gnome, because on Gnome some apps will have menubar and toolbar under windows decorations, if I make it as same height as csd windows that will make some app like inkscape gimp ... looks not as compact as csd apps, so I think I should better keep this not to change it.
