### ISSUE TITLE
[Request] Make Qogir available on Flathub

### ISSUE THREAD

**Issue by aasril** [vinceliuice/Qogir-theme#71]
I use a flatpak installed application which apparently doesn't use Gtk theme (Qogir). My understanding is, flatpak apps will follow the system theme if I also have the same theme installed with flatpak. I looked at it and Qogir doesn't available in Flathub.

I don't know how much work it is, but it would be great if Qogir is also available in Flathub.

**Comment by aasril** [comment]
I've just tried it and confirm that flatpak applications will follow system Gtk theme if I also installed the same theme with flatpak. 

I tried with Materia theme.

**Comment by jairoraiol** [comment]
It would be good if it were available as well.

**Comment by FunkenTom** [comment]
I would have the same request

**Comment by notsrijit** [comment]
Yes please, I second this.

**Comment by jpmgsxr** [comment]
I'm with him ^

**Comment by Abhinav1217** [comment]
Hi, I have been using this theme for quite some time, But now since I have started using flatpak apps over distro apps, I am missing out on this beautiful theme. Please make it available on the flathub.

**Comment by happydemic** [comment]
Hi @vinceliuice - thanks so much for putting Qogir on Flathub. Looks great! 

I noticed that most selected / accented items appear blue in the Flathub versions of Qogir-Ubuntu and Qogir-Manjaro. Only certain types of accent in the Flathub versions use the distro-inspired colour of that form of Qogir (Ubuntu orange or Manjaro green).

This is inconsistent with desktop Qogir, because desktop versions use the same colour for all selections / highlights. See picture, showing:
- the consistent orange colours of selections using Qogir Ubuntu in desktop apps (Nautilus and Tweak Tool).
- the inconsistent colours of selections with Flathub Qogir Ubuntu in a flatpak app (Gradio). 
Selected items in the flatpak app appear blue, and the orange colour appears in the flatpak app only for the checkboxes. The blue highlight is not hardcoded by Gradio, and is themed correctly in other flatpak themes: Adapta, Matcha, etc.

![Flathub vs Unity](https://user-images.githubusercontent.com/12738878/69319203-a5580d80-0c36-11ea-8d63-77b149e81d96.png)

It would be great to have a perfect match between desktop and flatpak apps in all Qogir versions.

**Comment by zeten30** [comment]
Hi All, 

there are already all Qogir variants on flathub:

https://github.com/flathub?q=Qogir&type=&language=

Recently updated (https://flathub.org/builds/#/)

Cheers

**Comment by vinceliuice** [comment]
Thanks @zeten30
